name: utilisateur-service
version: '3.8'
services:
  db:
    image: postgres:13
    container_name: utilisateur-container
    volumes:
      - postgres_data_utilisateur:/var/lib/postgresql/data
      - ./initUtilisateur.sql:/docker-entrypoint-initdb.d/initUtilisateur.sql
    environment:
      POSTGRES_DB: utilisateur_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"

volumes:
  postgres_data_utilisateur: