version: '3.8'
services:
  db:
    image: postgres:13
    container_name: contactLabo-service
    volumes:
      - postgres_data_contactLabo:/var/lib/postgresql/data
      - ./initAnalyse.sql:/docker-entrypoint-initdb.d/initContactLabo.sql
    environment:
      POSTGRES_DB: contactLabo-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"

volumes:
  postgres_data_contactLabo:
