version: '3.8'

services:
  dossier_db:
    image: postgres:13
    volumes:
      - postgres_data_dossier:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: dossier_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5439:5432"
    networks:
      - dossier-network

  selenium-hub:
    image: selenium/standalone-chrome:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - dossier-network

  dossier-service:
    build: ./dossier-service
    container_name: dossier-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - dossier_db
      - selenium-hub
    networks:
      - dossier-network

volumes:
  postgres_data_dossier:

networks:
  dossier-network:
    driver: bridge
