name: adresse-service
version: '3.8'
services:
  db:
    image: postgres:13
    container_name: adresse-service
    volumes:
      - postgres_data_adresseService:/var/lib/postgresql/data
      - ./initAdresse.sql:/docker-entrypoint-initdb.d/initAdresse.sql
    environment:
      POSTGRES_DB: adresse-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432"

volumes:
  postgres_data_adresseService:
